In [1]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [ ]:
print(x)

In [5]:
x = [1,2,3]

In [ ]:
x

In [7]:
x.append(2)

In [ ]:
x

In [9]:
x = [1, 'Caio', 3]

In [ ]:
x

In [11]:
x = np.ones((5, 5))

In [ ]:
x

In [13]:
x = np.eye(4)

In [ ]:
x

In [16]:
x = np.arange(5, 10, 2)

In [ ]:
x

In [18]:
x = np.array([[1, 2, 3]] * 5)

In [19]:
x

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
y = np.array([[2, 2, 2]]*5)

In [21]:
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [22]:
x + y

array([[3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5]])

In [23]:
x - y

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [24]:
x/y

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [25]:
x * y

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])